#! /usr/bin/env python

"""
This ROS node uses the object detector class to run detection.
"""

from object_detector import ObjectDetector
from PIL import Image

#ros
import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
from object_detection.msg import DetectionResult
from object_detection.msg import DetectionResults


class ObjectDetectionNode:

    def __init__(self):

        rospy.init_node('object_detection')
        rospy.Subscriber('/camera_node/image_raw', Image, callback=self.image_update_callback, queue_size=5)

        self.current_frame = None
        self.bridge = CvBridge()

        rospy.loginfo("Object Detection Initializing")
        rospy.loginfo("Tiny Yolo V3")

        self.visualize = rospy.get_param("/object_detection_node/visualization")
        self.model_path = rospy.get_param("/object_detection_node/model_path")
        self.classes_path = rospy.get_param("/object_detection_node/classes_path")
        self.anchors_path = rospy.get_param("/object_detection_node/anchors_path")
        self.iou_threshold = rospy.get_param("/object_detection_node/iou_threshold")
        self.score_threshold = rospy.get_param("/object_detection_node/score_threshold")
        self.input_size = (416, 416)

        self.detector = ObjectDetector(model_path=self.model_path,
                                       classes_path=self.classes_path,
                                       anchors_path=self.anchors_path,
                                       score_threshold=self.score_threshold,
                                       iou_threshold=self.iou_threshold,
                                       size=self.input_size)

        detection_image_pub = rospy.Publisher('/detection/object/detection_visualization/', Image, queue_size=10)
        detection_results_pub = rospy.Publisher('/detection/object/detection_result', DetectionResults, queue_size=10)
        rate = rospy.Rate(15)

        while not rospy.is_shutdown():
            if self.current_frame is not None:
                image, out_boxes, out_scores, out_classes = \
                    self.detector.detect_object(self.current_frame, visualize=self.visualize)
                img_msg = self.bridge.cv2_to_imgmsg(image, "bgr8")
                detection_image_pub.publish(img_msg)
                msg = self.convert_results_to_message(out_boxes, out_scores, out_classes)
                detection_results_pub.publish(msg)
            rate.sleep()

    def image_update_callback(self, data):
        try:
            cv_image = self.bridge.imgmsg_to_cv2(data, "bgr8")
        except CvBridgeError as e:
            raise e

        self.current_frame = cv_image

    @staticmethod
    def convert_results_to_message(out_boxes, out_scores, out_classes):

        msgs = DetectionResults()
        for i in range(len(out_scores)):
            msg = DetectionResult()
            msg.out_class = out_classes[i]
            msg.out_score = out_scores[i]
            msg.location = out_boxes[i, :]
            msgs.results.append(msg)

        return msgs


if __name__ == "__main__":

    try:
        ObjectDetectionNode()
    except rospy.ROSInterruptException:
        pass
